Import Libraries :

In [24]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [25]:
iris = load_iris()

A.Load Dataset using Pandas

In [26]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

In [39]:
print("First 5 Rows of Dataset:")
print(df.head())
print("KHUSHI")

First 5 Rows of Dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0
KHUSHI

B. Basic Preprocessing

In [36]:
# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Features and Target
X = df.iloc[:, :-1]
y = df['target']

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Missing Values:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [42]:
#Load Dataset
df = pd.read_csv("iris - iris.csv")

In [ ]:
#Display Dataset
print("\nDataset")
print(df.head())

Dataset
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:
# Check dataset information
print("\nDataset Information")
print(df.info())

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
None

In [44]:
# Dataset Shape
print("\nShape")
print(df.shape)

Shape
(150, 5)

In [45]:
# Column Names
print("\nColumns")
print(df.columns)

Columns
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [46]:
#  Summary Statistics
print("\nSummary Statistics")
print(df.describe())

Summary Statistics
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [47]:
#  Data Types
print("\nData Types")
print(df.dtypes)

Data Types
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [48]:
#  Missing Values
print("\nMissing Values")
print(df.isnull().sum())

Missing Values
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [49]:
# Handle Missing Values
df.fillna(df.select_dtypes(include="number").mean(), inplace=True)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [59]:
# Remove Duplicate Records
df.drop_duplicates(inplace=True)
print(df.drop)

<bound method DataFrame.drop of      Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]>

In [60]:
#  Encode Categorical Data
encoder = LabelEncoder()
df["species"] = encoder.fit_transform(df["species"])
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

In [61]:
#  Rename Columns
df.rename(columns={
    "sepal_length":"Sepal_Length",
    "sepal_width":"Sepal_Width",
    "petal_length":"Petal_Length",
    "petal_width":"Petal_Width"
}, inplace=True )
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

In [ ]:
#  Drop Unnecessary Columns
# No unnecessary columns in Iris dataset

In [62]:
#  Feature Selection
X = df.drop("species", axis=1)
y = df["species"]
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

In [63]:
#  Feature Engineering
df["Total_Length"] = df["Sepal_Length"] + df["Petal_Length"]
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

In [65]:
# Convert Data Types
df["species"] = df["species"].astype("int")

# Normalize Data
minmax = MinMaxScaler()
X_normalized = minmax.fit_transform(X)

# Standardize Data
standard = StandardScaler()
X_standardized = standard.fit_transform(X)

# Split Features & Target
X_train, X_test, y_train, y_test = train_test_split(
    X_standardized,
    y,
    test_size=0.2,
    random_state=42
)
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

C. Split Dataset into Training and Testing Sets

In [77]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

D.Train a Simple Classifier

In [78]:
classifier = DecisionTreeClassifier(random_state=42)
classifier.fit(X_train, y_train)

#  Predict
train_pred = classifier.predict(X_train)
test_pred = classifier.predict(X_test)

# Display Accuracy
train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)
print(df)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  species  \
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

     Total_Length
0             6.5
1             6.3
2             6.0
3             6.1
4             6.4
..            ...
145          11.9
146          11.3
147          11.7
148          11.6
149          11.0

[147 rows x 6 columns]

E. Display training & testing accuracy

In [35]:
print("\nTraining Accuracy:", round(train_accuracy * 100, 2), "%")
print("Testing Accuracy:", round(test_accuracy * 100, 2), "%")
print("KHUSHI T032")

Training Accuracy: 100.0 %
Testing Accuracy: 100.0 %
KHUSHI T032

B] Mall_Customers.csv

In [79]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [120]:
df = pd.read_csv("Mall_Customers.csv")
print(df)

   CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0                                     1,Male,19,15,39
1                                     2,Male,21,15,81
2                                    3,Female,20,16,6
3                                   4,Female,23,16,77
4                                   5,Female,31,17,40
5                                   6,Female,22,17,76
6                                    7,Female,35,18,6
7                                   8,Female,23,18,94
8                                      9,Male,64,19,3
9                                  10,Female,30,19,72
10                                   11,Male,67,19,14
11                                 12,Female,35,19,99
12                                 13,Female,58,20,15
13                                 14,Female,24,20,77
14                                   15,Male,37,20,13
15                                   16,Male,22,20,79
16                                 17,Female,35,21,35
17                                   18,Male,20,21,66
18                                   19,Male,52,23,29
19                                 20,Female,35,23,98
20                                   21,Male,35,24,35
21                                   22,Male,25,24,73
22                                  23,Female,46,25,5
23                                   24,Male,31,25,73
24                                 25,Female,54,28,14
25                                   26,Male,29,28,82
26                                 27,Female,45,28,32
27                                   28,Male,35,28,61
28                                 29,Female,40,29,31
29                                 30,Female,23,29,87

In [81]:
print("First 5 Records")
print(df.head())

First 5 Records
  CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0                                    1,Male,19,15,39
1                                    2,Male,21,15,81
2                                   3,Female,20,16,6
3                                  4,Female,23,16,77
4                                  5,Female,31,17,40

In [82]:
print("\nDataset Information")
print(df.info())

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 1 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)  30 non-null     str
dtypes: str(1)
memory usage: 372.0 bytes
None

In [83]:
print("\nDataset Shape")
print(df.shape)

Dataset Shape
(30, 1)

In [84]:
print("\nColumn Names")
print(df.columns)

Column Names
Index(['CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)'], dtype='str')

In [85]:
print("\nSummary Statistics")
print(df.describe())

Summary Statistics
       CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
count                                                  30
unique                                                 30
top                                       1,Male,19,15,39
freq                                                    1

In [86]:
print("\nData Types")
print(df.dtypes)

Data Types
CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)    str
dtype: object

In [87]:
print("\nMissing Values")
print(df.isnull().sum())

Missing Values
CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)    0
dtype: int64

In [88]:
df.fillna(df.select_dtypes(include='number').mean(), inplace=True)

   CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0                                     1,Male,19,15,39
1                                     2,Male,21,15,81
2                                    3,Female,20,16,6
3                                   4,Female,23,16,77
4                                   5,Female,31,17,40
5                                   6,Female,22,17,76
6                                    7,Female,35,18,6
7                                   8,Female,23,18,94
8                                      9,Male,64,19,3
9                                  10,Female,30,19,72
10                                   11,Male,67,19,14
11                                 12,Female,35,19,99
12                                 13,Female,58,20,15
13                                 14,Female,24,20,77
14                                   15,Male,37,20,13
15                                   16,Male,22,20,79
16                                 17,Female,35,21,35
17                                   18,Male,20,21,66
18                                   19,Male,52,23,29
19                                 20,Female,35,23,98
20                                   21,Male,35,24,35
21                                   22,Male,25,24,73
22                                  23,Female,46,25,5
23                                   24,Male,31,25,73
24                                 25,Female,54,28,14
25                                   26,Male,29,28,82
26                                 27,Female,45,28,32
27                                   28,Male,35,28,61
28                                 29,Female,40,29,31
29                                 30,Female,23,29,87

In [90]:
df.drop_duplicates(inplace=True)
print(df)

   CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0                                     1,Male,19,15,39
1                                     2,Male,21,15,81
2                                    3,Female,20,16,6
3                                   4,Female,23,16,77
4                                   5,Female,31,17,40
5                                   6,Female,22,17,76
6                                    7,Female,35,18,6
7                                   8,Female,23,18,94
8                                      9,Male,64,19,3
9                                  10,Female,30,19,72
10                                   11,Male,67,19,14
11                                 12,Female,35,19,99
12                                 13,Female,58,20,15
13                                 14,Female,24,20,77
14                                   15,Male,37,20,13
15                                   16,Male,22,20,79
16                                 17,Female,35,21,35
17                                   18,Male,20,21,66
18                                   19,Male,52,23,29
19                                 20,Female,35,23,98
20                                   21,Male,35,24,35
21                                   22,Male,25,24,73
22                                  23,Female,46,25,5
23                                   24,Male,31,25,73
24                                 25,Female,54,28,14
25                                   26,Male,29,28,82
26                                 27,Female,45,28,32
27                                   28,Male,35,28,61
28                                 29,Female,40,29,31
29                                 30,Female,23,29,87

In [100]:
df.columns = df.columns.str.strip()

print(df.columns)

Index(['CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)'], dtype='str')

In [94]:
df.rename(columns={
    "Annual Income (k$)": "Annual_Income",
    "Spending Score (1-100)": "Spending_Score"
}, inplace=True)
print(df)

   CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0                                     1,Male,19,15,39
1                                     2,Male,21,15,81
2                                    3,Female,20,16,6
3                                   4,Female,23,16,77
4                                   5,Female,31,17,40
5                                   6,Female,22,17,76
6                                    7,Female,35,18,6
7                                   8,Female,23,18,94
8                                      9,Male,64,19,3
9                                  10,Female,30,19,72
10                                   11,Male,67,19,14
11                                 12,Female,35,19,99
12                                 13,Female,58,20,15
13                                 14,Female,24,20,77
14                                   15,Male,37,20,13
15                                   16,Male,22,20,79
16                                 17,Female,35,21,35
17                                   18,Male,20,21,66
18                                   19,Male,52,23,29
19                                 20,Female,35,23,98
20                                   21,Male,35,24,35
21                                   22,Male,25,24,73
22                                  23,Female,46,25,5
23                                   24,Male,31,25,73
24                                 25,Female,54,28,14
25                                   26,Male,29,28,82
26                                 27,Female,45,28,32
27                                   28,Male,35,28,61
28                                 29,Female,40,29,31
29                                 30,Female,23,29,87

In [107]:
df.drop(columns=["CustomerID"], errors="ignore", inplace=True)
print(df.columns.tolist())

['CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)']